---
title: 'Attitudes Experiment 2: Plots'
author: "Simon van Baal"
date: "22/10/2021"
output: html_document
---

```{r setup, include=FALSE}
library(ggpubr)
```

```{r Graphs}
dataExp2 <- 
  dataExp2 %>% 
  mutate(PerspectiveNumeric = ifelse(Perspective == "Self", 1, 0))

# The palette with black:
cbbPalette <- c("#000000", "#E69F00", 
                "#56B4E9", "#009E73", 
                "#F0E442", "#0072B2", 
                "#D55E00", "#CC79A7")
cbbPaletteBoxPlots <- c("#E69F00","#56B4E9","#000000")
## Plot dimensions
w = 6
h = 4

Midpoint_Density <- 
  ggplot(dataExp2 %>% 
           filter(vasMarker == "Midpoint"), 
         aes(x = VAS, fill = Perspective)) +
  geom_density(alpha = 0.4) +
  geom_boxplot(aes(x = VAS, y = PerspectiveNumeric * -0.0015 + 0.05), alpha = .4, colour = "black",notch = TRUE, coef = 1 ) +
  labs(title = "VAS Midpoint") + 
  ylab("Density") + 
  xlab("Permissiveness") +
  scale_fill_manual(values = cbbPalette) +
  theme_light()

NoMidpoint_Density <- 
  ggplot(dataExp2 %>% 
           filter(vasMarker == "No Midpoint"), 
         aes(x = VAS, fill = Perspective)) +
  geom_density(alpha = 0.4) +
  geom_boxplot(aes(x = VAS, y = PerspectiveNumeric * -0.0015 + 0.05), 
               alpha = .4, colour = "black",notch = TRUE, coef = 1 ) +
  labs(title = "No Midpoint") + 
  ylab("Density") + 
  xlab("Permissiveness") +
  scale_fill_manual(values = cbbPalette) +
  theme_light()

vasMarkerPlots <-
  ggarrange(
    Midpoint_Density,
    NoMidpoint_Density,
    labels = c("A", "B"),
    nrow = 1,
    ncol = 2,
    common.legend = TRUE,
    legend = "bottom"
  )
vasMarkerPlots
ggsave("./figures/DensityPlotExp2.png", width = 2*w, height = 1.3*h) 

################# Density plot of VAS per group
a <-
  ggplot(
    dataExp2 %>% filter(vasMarker == "Midpoint", Risk == "High Risk"),
    aes(x = VAS, fill = Perspective)
  ) +
  geom_density(alpha = 0.4) +
  geom_boxplot(
    aes(x = VAS, y = PerspectiveNumeric * 0.1 - 0.25),
    alpha = .4,
    colour = "black",
    notch = TRUE,
    outlier.alpha = .4,
    outlier.size = 1,
  ) +
  labs(title = "VAS Midpoint, High Risk") +
  ylab("Density") +
  xlab("Permissiveness") +
  lims(y = c(-0.3, 4.2)) +
  theme_light()

b <-
  ggplot(
    dataExp2 %>% filter(vasMarker == "Midpoint", Risk == "Low Risk"),
    aes(x = VAS, fill = Perspective)
  ) +
  geom_density(alpha = 0.4) +
  geom_boxplot(
    aes(x = VAS, y = PerspectiveNumeric * 0.1 - 0.25),
    alpha = .4,
    colour = "black",
    notch = TRUE,
    outlier.alpha = .4,
    outlier.size = 1,
  ) +
  labs(title = "VAS Midpoint, Low Risk") +
  xlab("Permissiveness") +
  lims(y = c(-0.3, 4.2)) +
  theme_light() +
  theme(axis.title.y = element_blank())

c <-
  ggplot(
    dataExp2 %>% filter(vasMarker == "Midpoint", Risk == "Minimal Risk"),
    aes(x = VAS, fill = Perspective)
  ) +
  geom_density(alpha = 0.4) +
  geom_boxplot(
    aes(x = VAS, y = PerspectiveNumeric * 0.1 - 0.25),
    alpha = .4,
    colour = "black",
    notch = TRUE,
    outlier.alpha = .4,
    outlier.size = 1,
  ) +
  labs(title = "VAS Midpoint, Minimal Risk") +
  xlab("Permissiveness") +
    lims(y = c(-0.3, 4.2)) +
  theme_light() +
  theme(axis.title.y = element_blank())

d <-
  ggplot(
    dataExp2 %>% filter(vasMarker == "No Midpoint", Risk == "High Risk"),
    aes(x = VAS, fill = Perspective)
  ) +
  geom_density(alpha = 0.4) +
  geom_boxplot(
    aes(x = VAS, y = PerspectiveNumeric * 0.1 - 0.25),
    alpha = .4,
    colour = "black",
    notch = TRUE,
    outlier.alpha = .4,
    outlier.size = 1,
  ) +
  labs(title = "No Midpoint, High Risk",
       x = "Permissiveness",
       y = "Density") +
  lims(y = c(-0.3, 4.2)) +
  theme_light() +
  theme(axis.title.y = element_blank())

e <-
  ggplot(
    dataExp2 %>% filter(vasMarker == "No Midpoint", Risk == "Low Risk"),
    aes(x = VAS, fill = Perspective)
  ) +
  geom_density(alpha = 0.4) +
  geom_boxplot(
    aes(x = VAS, y = PerspectiveNumeric * 0.1 - 0.25),
    alpha = .4,
    colour = "black",
    notch = TRUE,
    outlier.alpha = .4,
    outlier.size = 1,
  ) +
  labs(title = "No Midpoint, Low Risk",
       x = "Permissiveness") +
    lims(y = c(-0.3, 4.2)) +
  theme_light() +
  theme(axis.title.y = element_blank())

f <-
  ggplot(
    dataExp2 %>% filter(vasMarker == "No Midpoint", Risk == "Minimal Risk"),
    aes(x = VAS, fill = Perspective)
  ) +
  geom_density(alpha = 0.4) +
  geom_boxplot(
    aes(x = VAS, y = PerspectiveNumeric * 0.1 - 0.25),
    alpha = .4,
    colour = "black",
    notch = TRUE,
    outlier.alpha = .4,
    outlier.size = 1,
  ) +
  labs(title = "No Midpoint, Minimal Risk",
       x = "Permissiveness") +
  lims(y = c(-0.3, 4.2)) +
  theme_light() +
  theme(axis.title.y = element_blank())


RiskPlots_Exp2 <- 
  ggarrange(a, b, c, d, e, f ,
            labels = c("A", "B", "C", "D", "E", "F"), 
            nrow = 2, ncol = 3, common.legend = TRUE, legend = "bottom")
ggsave("./figures/RiskPlotsExp2.png", width = 2.25*w, height = 1.875*h) 

RiskPlots_Exp2

```


```{r plots cont'd}
################################################## Box Plots


boxRiskExp2 <-
  ggplot(dataExp2 %>%
           mutate(Risk = factor(
             Risk,
             levels = c("Minimal Risk",
                        "Low Risk", "High Risk")
           )),
         aes(x = VAS, y = Risk, fill = Risk)) +
  geom_boxplot(
    position = position_nudge(y = 0.25),
    outlier.shape = NA,
    notch = TRUE,
    width = 0.2
  ) +
  geom_point(position = position_jitter(height = 0.1),
             size = .15,
             col = "darkgrey") +
  annotate(
    "segment",
    x = c(-.03, -.03, -.08),
    xend = c(-.03, -.03, -.08),
    y = c(1.23, 2.27, 1.18),
    yend = c(2.22, 3.22, 3.30),
    size = .8
  ) +
  annotate(
    "text",
    x = c(-.035, -.035, -.09),
    y = c(1.75, 2.75, 2.25),
    label = "**",
    angle = 90,
    size = 7
  ) +
  labs(title = "Permissiveness by Risk Level") +
  xlab("Permissiveness") + ylab("Risk Level") +
  xlim(-.10, 1.005) +
  scale_fill_brewer(palette = "YlOrRd") +
  guides(fill = guide_legend(reverse = TRUE)) +
  theme_light()
boxRiskExp2
ggsave("./figures/exp2RiskBoxPlot.png", width = w, height = h)




```



```{r Plots continued #2}

RiskAggregates <- 
  dataExp2 %>%
  group_by(ResponseId, Sex, Risk) %>%
  summarise(VAS = mean(VAS),
            Age = mean(Age)) %>%
  ungroup()

AgeSexPlotExp2 <- 
  ggplot(Aggregates) +
    aes(x = Age, y = VAS, col = Sex) +
    geom_point() +
    geom_smooth(method = "lm") +
    labs(y = "Permissiveness") +
    scale_colour_viridis_d(begin = .3, end = .75) +
    theme_light()
AgeSexPlotExp2
ggsave("./figures/AgeSexExp2.png", height = h*.95, width = w*.95)

AgeRiskPlotExp2 <-
  ggplot(RiskAggregates) +
    aes(x = Age, y = VAS, col = Risk) +
    geom_point(size = 1) +
    geom_smooth(method = "lm") +
    labs(y = "Permissiveness") +
    scale_colour_brewer(palette = "YlOrRd") +
    theme_light()

PlotsAgeExp2 <- 
  ggarrange(AgeRiskPlotExp2, AgeSexPlotExp2,
            labels = c("A", "B"), 
            nrow = 1, ncol = 2, 
            common.legend = FALSE, legend = "bottom")
ggsave("./figures/AgePlotsExp2.png", width = 2*w, height = 1.3*h) 

Aggregates <-
  Aggregates %>% 
  arrange(VAS) %>% 
  mutate(VAS_Rank = seq(1:nrow(Aggregates))/nrow(Aggregates)*100)


```

