---
title: "Cleaning Script Self-Isolation Experiment 1"
author: "Simon van Baal"
date: "20/09/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(renv)

renv::init()
```

```{r load data, include=FALSE}

# Don't mind the errors, that's due to the column names Qualtrics creates.
RawData <- read_csv("./raw-data/SelfIsolationFirstBatch.csv")
RawData2 <- read_csv("./raw-data/SelfIsolationSecondBatch.csv")

# Here we put together the first bit of the dataset, before we added in the 'Group' column.
dataExp1 <- bind_rows(RawData, RawData2)

rm(RawData, RawData2)

```

```{r Data cleaning, include = FALSE}
# NAs for all the observations except the treatment received need to be removed, 
# and we're not interested in reaction times.

dataExp1 <- 
  dataExp1 %>% 
  filter(Finished == TRUE) %>% 
  select(-ReadingQ, -contains("RT"))


#Personal, personal responsibility
personalResponsibilityData <- 
  dataExp1 %>%
  filter(!is.na(`1_Per_Rea_1`) | Group == "Personal Reasoning") %>%
  select_if(function(x)
    ! any(is.na(x))) %>%
  mutate(Perspective = "Personal",
         Communication = "Personal Responsibility")

#Personal, imperative
personalImperativeData <- 
  dataExp1 %>% 
  filter(!is.na(`1_Per_Imp_1`) | Group == "Personal Imperative") %>% 
  select_if(function(x) !any(is.na(x))) %>% 
  mutate(Perspective = "Personal",
         Communication = "Imperative")

#General, personal responsibility
generalResponsibilityData <- 
  dataExp1 %>% 
  filter(!is.na(`1_Gen_Rea_1`)) %>% 
  select_if(function(x) !any(is.na(x))) %>% 
  mutate(Perspective = "General",
         Communication = "Personal Responsibility")

#General, imperative
generalImperativeData <- 
  dataExp1 %>% 
  filter(!is.na(`1_Gen_Imp_1`)) %>% 
  select_if(function(x) !any(is.na(x)))  %>% 
  mutate(Perspective = "General",
         Communication = "Imperative")

#Personal Control
personalControlData <- 
  dataExp1 %>% 
  filter(!is.na(`1_Per_Con_1`)) %>% 
  select_if(function(x) !any(is.na(x))) %>% 
  mutate(Perspective = "Personal",
         Communication = "Control")

#General Control
generalControlData <- 
  dataExp1 %>% 
  filter(!is.na(`1_Gen_Con_1`)) %>% 
  select_if(function(x) !any(is.na(x))) %>% 
  mutate(Perspective = "General",
         Communication = "Control")

#Now rbind the 12 datasets created.
colnames(personalResponsibilityData) <- colnames(generalControlData)
colnames(personalImperativeData) <- colnames(generalControlData)
colnames(generalResponsibilityData) <- colnames(generalControlData)
colnames(generalImperativeData) <- colnames(generalControlData)
colnames(personalControlData) <- colnames(generalControlData)

dataExp1 <- 
  rbind(personalResponsibilityData, personalImperativeData, 
        generalResponsibilityData, generalImperativeData, 
        personalControlData, generalControlData)

rm(personalResponsibilityData, personalImperativeData, generalResponsibilityData, generalImperativeData, personalControlData, generalControlData)

#Rearrange and rename columns
dataExp1 <- 
  dataExp1 %>% 
  as_tibble() %>% 
  select(-Practice_Gen_1,
         ResponseId, Perspective, 
         Communication,  
         ends_with("_1"), everything())

names(dataExp1)[5:34] <- 
  sprintf("Question_%s",seq(1:30))

dataExp1 <- 
  dataExp1 %>% 
  select(ResponseId, Perspective, Communication, 
         contains("Question"), Age_1, 
         Sex, Eng, Res)

write_csv(dataExp1, "./data/going-out_experiment1_data.csv")


```

```{r Cleaning}
# Risk level categorisation sequence
RiskLevelSequence <- 
  c("Low Risk", "High Risk", "Minimal Risk",
  "High Risk", "High Risk", "Low Risk",
  "High Risk", "High Risk", "Minimal Risk",
  "High Risk", "Minimal Risk", "High Risk",
  "Minimal Risk", "Minimal Risk", "Minimal Risk",
  "Low Risk", "High Risk", "Low Risk",
  "Low Risk", "High Risk", "Low Risk",
  "High Risk", "High Risk", "Minimal Risk",
  "High Risk", "High Risk", "Low Risk",
  "High Risk", "High Risk", "High Risk"
  )

#Create long data.
dataExp1 <-
  dataExp1 %>%
  gather(
    key = "Question",
    value = "VAS",
    Question_1:Question_30,
    factor_key = TRUE
  ) %>%
  arrange(ResponseId) %>%
  mutate(Risk = rep(
    RiskLevelSequence,
  times = nrow(dataExp1)),
  Age = Age_1,
  Age_1 = NULL,
  VAS = VAS/100)

## VAS indicates on a scale from 0-1 to what extent the participant is certain 
# that it is ok to go out (certain it is not alright - certain it is alright)

dataExp1 <-
  dataExp1 %>%
  group_by(ResponseId) %>%
  filter(Res == "United Kingdom of Great Britain and Northern Ireland") %>%
  ungroup() %>% 
  mutate(Perspective = factor(Perspective), 
         Communication = relevel(factor(Communication), ref = "Control"),
         Risk = factor(Risk),
         Sex = factor(Sex),
         AgeZeroCenter = scale(Age, center = T, scale = F),
         ResponseId = factor(ResponseId))


```


