---
title: 'Attitudes Experiment 1: Plots'
author: "Simon van Baal"
date: "22/10/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(cowplot)
library(ggsignif)
library(ggpubr)
```


```{r Graphs}
dataExp1 <-
  dataExp1 %>%
  mutate(CommunicationNumeric =
           ifelse(
             Communication == "Imperative",
             2,
             ifelse(Communication == "Personal Responsibility", 3, 1)
           ),
         VAS = VAS/100)

# The palette with black:
cbbPalette <- c(
  "#000000",
  "#E69F00",
  "#56B4E9",
  "#009E73",
  "#F0E442",
  "#0072B2",
  "#D55E00",
  "#CC79A7"
)
cbbPaletteBoxPlots <- c("#E69F00","#56B4E9","#000000")
## Plot dimensions
w = 6
h = 4


#################33 Density plot of VAS per group
a <- ggplot(dataExp1 %>% filter(Perspective == "Personal", Risk == "High Risk"), 
       aes(x = VAS, fill = Communication)) +
  geom_density(alpha = 0.4) +
  geom_boxplot(aes(x = VAS, y = CommunicationNumeric * -0.0015 + 0.05), 
               alpha = .4, colour = "black",
               notch = TRUE, coef = 1 ) +
  labs(title = "High Risk, Self Framing") + 
  labs(x = "Permissiveness", y = "Density") +
  theme_light()

b <- ggplot(dataExp1 %>% filter(Perspective == "Personal", Risk == "Low Risk"), 
       aes(x = VAS, fill = Communication)) +
  geom_density(alpha = 0.4) +
  geom_boxplot(aes(x = VAS, y = CommunicationNumeric * -0.0015 + 0.05), alpha = .4, colour = "black", notch = TRUE, coef = 1 ) +
labs(title = "Low Risk, Self Framing") + ylab("") + xlab("Permissiveness") +
  theme_light()

c <- ggplot(dataExp1 %>% filter(Perspective == "Personal", Risk == "Minimal Risk"),
       aes(x = VAS, fill = Communication)) + 
  geom_density(alpha = 0.4) +
  geom_boxplot(aes(x = VAS, y = CommunicationNumeric * -0.0015 + 0.05), alpha = .4, colour = "black", notch = TRUE, coef = 1 ) +
  labs(title = "Minimal Risk, Self Framing") + ylab("") + xlab("Permissiveness") +
  theme_light()

d <- ggplot(dataExp1 %>% filter(Perspective == "General", Risk == "High Risk"), 
       aes(x = VAS, fill = Communication)) +
  geom_density(alpha = 0.4) +
  geom_boxplot(aes(x = VAS, y = CommunicationNumeric * -0.0015 + 0.05), alpha = .4, colour = "black", notch = TRUE, coef = 1 ) +
  labs(title = "High Risk, Other Framing") + ylab("Density") + xlab("Permissiveness") +
  theme_light()

e <- ggplot(dataExp1 %>% filter(Perspective == "General", Risk == "Low Risk"), 
       aes(x = VAS, fill = Communication)) +
  geom_density(alpha = 0.4) +
  geom_boxplot(aes(x = VAS, y = CommunicationNumeric * -0.0015 + 0.05), alpha = .4, colour = "black", notch = TRUE, coef = 1 ) +
  labs(title = "Low Risk, Other Framing") + ylab("") + xlab("Permissiveness") +
  theme_light()

f <- ggplot(dataExp1 %>% filter(Perspective == "General", Risk == "Minimal Risk"), 
       aes(x = VAS, fill = Communication)) +
  geom_density(alpha = 0.4) +
  geom_boxplot(aes(x = VAS, y = CommunicationNumeric * -0.0015 + 0.05), alpha = .4, colour = "black", notch = TRUE, coef = 1 ) +
  labs(title = "Minimal Risk, Other Framing") + ylab("") + xlab("Permissiveness") +
  theme_light()


DensityPlots <- ggarrange(a, b, c, d, e, f ,
                          labels = c("A", "B", "C", "D", "E", "F"), 
                          nrow = 2, ncol = 3, 
                          common.legend = TRUE, legend = "bottom")
ggsave("./figures/DensityPlot.png", width = 3*w, height = 2.5*h) 

DensityPlots

################################################## Box Plots


boxRisk <-
  ggplot(arrange(dataExp1 %>%
                   mutate(Risk = factor(
                     ifelse(
                       Risk == "Minimal Risk", 
                       "Minimal", 
                       ifelse(
                         Risk == "Low Risk",
                         "Low",
                         "High"
                       )
                     ),
                     levels = c("Minimal", 
                                "Low", 
                                "High")
                   ))),
         aes(x = VAS, y = Risk, fill = Risk)) +
  geom_boxplot(
    position = position_nudge(y = 0.25),
    outlier.shape = NA,
    notch = TRUE,
    width = 0.2
  )+
  geom_point(position = position_jitter(height = 0.1),
             size = .15,
             col = "darkgrey") +
  annotate(
    "segment",
    x = c(-.03, -.03, -.08),
    xend = c(-.03, -.03, -.08),
    y = c(1.23, 2.27, 1.17),
    yend = c(2.22, 3.22, 3.30),
    size = .8
  ) +
  annotate(
    "text",
    x = c(-.035, -.035, -.09),
    y = c(1.75, 2.75, 2.25),
    label = "***",
    angle = 90,
    size = 7
  ) +
  labs(title = "Permissiveness by Risk Level") +
  xlab("Permissiveness") + ylab("Risk") +
  xlim(-.1, 1.005) +
  scale_fill_brewer(palette = "YlOrRd") +
  guides(fill = guide_legend(reverse = T)) +
  labs(tag = "1A") +
  theme_light() +
  theme(axis.text.y = element_blank())
boxRisk

boxComm <-
  ggplot(dataExp1 %>%
           mutate(Communication = factor(
             ifelse(Communication == "Personal Responsibility", 
                    "Personal Resp.",
                    ifelse(Communication == "Imperative",
                           "Imperative",
                           "Control")), levels = c(
               "Control", "Personal Resp.","Imperative"
             )
           )),
         aes(x = VAS, y = Communication, fill = Communication)) +
  geom_boxplot(
    position = position_nudge(y = 0.25),
    outlier.shape = NA,
    notch = TRUE,
    width = 0.2
  ) +
  geom_point(position = position_jitter(height = 0.1),
             size = .15,
             col = "darkgrey") +
  annotate(
    "segment",
    x = c(-.03, -.03, -.075),
    xend = c(-.03, -.03, -.075),
    y = c(1.23, 2.27, 1.17),
    yend = c(2.22, 3.22, 3.30),
    size = .8
  ) +
  annotate(
    "text",
    x = c(-.035, -.055, -.09),
    y = c(1.75, 2.75, 2.25),
    label = c("*", "n.s.", "**"),
    angle = 90,
    size = c(7, 5, 7)
  ) +
  labs(title = "Permissiveness by Communication Style") +
  xlab("Permissiveness") + 
  ylab("Communication Style") +
  xlim(-.1, 1.005) +
  guides(fill = guide_legend("Communication", reverse = T)) +
  scale_fill_manual(values = cbbPalette[c(9, 3, 2)]) +
  labs(tag = "1B") +
  theme_light() +
  theme(axis.text.y = element_blank())
boxComm

BoxPlots <-
  ggarrange(
    boxRisk,
    boxComm,
    nrow = 1,
    ncol = 2,
    common.legend = F,
    legend = "bottom"
  )
ggsave("./figures/BoxPlot.png", width = 2*w, height = 1.3*h)
BoxPlots

```

```{R Plots continued}

############################ Raincloud plot
#source("Raincloudplot.R")



j <- ggplot(dataExp1 %>% filter(Perspective == "Personal"),
       aes(x = Communication, y = VAS, fill = Communication, alpha = 0.4)) +
    geom_flat_violin(position = position_nudge(x = .2, y = 0),adjust = .8)+
  geom_point(position = position_jitter(width = .15), size = .25)+
  geom_boxplot(aes(x = CommunicationNumeric + 0.2, y = VAS), outlier.shape = NA, width = .07, colour = "BLACK", alpha = 1) + 
  ylab('Permissiveness')+xlab('')+coord_flip()+theme_cowplot()+guides(fill = FALSE, alpha = FALSE, colour = FALSE) +
  scale_fill_manual(values = cbbPalette)+
  labs(tag = "A")

k <- ggplot(dataExp1 %>% filter(Perspective == "General"),
       aes(x = Communication, y = VAS, fill = Communication, alpha = 0.4)) +
    geom_flat_violin(position = position_nudge(x = .2, y = 0),adjust = .8)+
  geom_point(position = position_jitter(width = .15), size = .25)+
  geom_boxplot(aes(x = CommunicationNumeric + 0.2, y = VAS), outlier.shape = NA, width = .07, colour = "BLACK", alpha = 1) + 
  ylab('Permissiveness')+xlab('')+coord_flip()+theme_cowplot()+guides(fill = FALSE, alpha = FALSE, colour = FALSE) +
  scale_fill_manual(values = cbbPalette)+
  labs(tag = "B") +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

rainCloudPlots <- 
  ggarrange(j, k, ncol = 2, nrow = 1)
ggsave('./figures/RaincloudPlot.png', width = w*2, height = h*2)


####################### Plot 2 and 3 (interactions)
my_grob <-
  grobTree(textGrob(
    "Limits: [0,100]",
    x = 0.01,
    y = 0.98,
    hjust = 0,
    gp = gpar(
      col = "black",
      fontsize = 10,
      fontface = "italic"
    )
  ))


df <- 
  summary(ComRiskEmm) %>% 
  arrange(Communication)

gd <- 
  dataExp1 %>% 
  group_by(Communication, Risk) %>% 
  summarise(Permissiveness = mean(VAS)) %>% 
  ungroup %>% 
  mutate(SE = df$SE)

comRiskPlot <-
  ggplot(
    dataExp1 %>%
      mutate(
        Communication = factor(
          ifelse(
            Communication == "Personal Responsibility",
            "Personal Resp.",
            ifelse(Communication == "Imperative", "Imperative", "Control")
          ),
          levels = c("Imperative", "Personal Resp.", "Control")
        ),
        Risk = factor(Risk, levels = c("Minimal Risk", "Low Risk", "High Risk"))
      ) %>%
      group_by(ResponseId, Risk, Communication) %>%
      summarise(VASmean = mean(VAS))
  ) +
  geom_boxplot(aes(Risk, VASmean, fill = Communication)) +
  labs(x = "Risk Level", y = "Permissiveness", fill = "Communication") +
  scale_fill_manual(values = cbbPalette[c(2,3,9)]) +
  theme_light()
ggsave("./figures/ComRiskBoxPlotExp1.png", w = 6, h = 5)

# ComRiskPlot <- ggplot(gd %>% mutate(Communication = factor(ifelse(Communication == "Personal Responsibility", "Personal Resp.",
#                                                                                  ifelse(Communication == "Imperative", "Imperative", "Control"))),
#                                      Risk = factor(Risk, levels = c("Minimal Risk", "Low Risk", "High Risk")))) +
#   aes(x = Risk, y = Permissiveness, color = Communication) +
#   geom_line(aes(group = Communication), size = 0.8) +
#   geom_point(aes(group = Communication), size = 2) +
#   geom_errorbar(aes(ymin=Permissiveness-SE, ymax=Permissiveness+SE), width=.1, size = 0.8) +
#   guides(color = guide_legend("Communication"), shape = FALSE) +
#   xlab("Risk Level") +
#   theme_light() +
#   annotation_custom(my_grob) +
#   scale_color_manual(values = cbbPalette) +
#   ggsave("InteractionPlot.png", width = w, height = 1.1*h)
#  ComRiskPlot

df2 <- summary(ExploratoryPairs) %>% filter(Risk == "High Risk") %>% arrange(Perspective, contrast)
gd2 <- dataExp1 %>%
  group_by(Communication, Perspective) %>%
  filter(Risk == "High Risk") %>%
  summarise(Permissiveness = mean(VAS)) %>%
  ungroup() %>%
  mutate(SE = df2$SE)

# HighRiskPerPlot <-  ggplot(gd2 %>% arrange(Perspective)) + 
#   aes(x = Perspective, y = Permissiveness, color = Communication) +
#   geom_line(aes(group = Communication), size = 1, position = position_dodge(width = .1)) +
#   geom_point(aes(group = Communication), position = position_dodge(width = .1), size = 2) +
#   geom_errorbar(aes(ymin = Permissiveness-SE, ymax = Permissiveness+SE), width = .15, size = 1, position = position_dodge(width = .1)) +
#   guides(color = guide_legend("Communication"), shape = FALSE) +
#   labs(tag = "4") +
#   guides() +
#   annotation_custom(my_grob) +
#   scale_color_manual(values = cbbPalette) +
#   theme_light() +
#   ggsave("ExploratoryPlot.png", width = w, height = 1.1*h)
# HighRiskPerPlot

df3 <-
  dataExp1 %>%
  group_by(ResponseId, Sex) %>%
  summarise(Age = mean(Age),
            Permissiveness = mean(VAS))

AgeSexPlotExp1 <-
  ggplot(df3) +
  aes(x = Age, y = Permissiveness, col = Sex) +
  geom_point() +
  geom_smooth(method = "lm") +
  scale_colour_viridis_d(begin = .25, end = .75) +
  theme_light()
ggsave("./figures/exp1AgeGenderPlot.png",
       width = 0.95 * w,
       height = 0.9 * h)


```
