---
title: 'Attitudes Experiment 2: Cleaning'
author: "Simon van Baal"
date: "22/10/2021"
output: html_document
---

```{r load data, include=FALSE}
# Don't mind the errors, that's due to the column names Qualtrics creates.
RawData_Self_Other <- read_csv("./raw-data/going-out_raw-data_no-marker.csv")
RawData_VAS <- read_csv("./raw-data/going-out_raw-data_midpoint.csv")
```

```{r Data cleaning, include = FALSE}
selfNoMarker <- 
  RawData_Self_Other %>% 
  filter(Group == "Self") %>% 
  select_if(function(x) !any(is.na(x))) %>%
  dplyr::select(-contains('RT'))

otherNoMarker <- 
  RawData_Self_Other %>%
  filter(Group == "Other") %>%
  select_if(function(x) !any(is.na(x))) %>%
  dplyr::select(-contains('RT'))

selfWithMarker <- 
  RawData_VAS %>% 
  filter(Group == "Self") %>% 
  select_if(function(x) !any(is.na(x))) %>%
  dplyr::select(-contains('RT'))

otherWithMarker <- 
  RawData_VAS %>%
  filter(Group == "Other") %>%
  select_if(function(x) !any(is.na(x))) %>%
  dplyr::select(-contains('RT'))

#Now rbind the 12 datasets created.
colnames(selfNoMarker) <- colnames(otherNoMarker)
colnames(selfWithMarker) <- colnames(otherNoMarker)
colnames(otherWithMarker) <- colnames(otherNoMarker)

dataExp2 <- 
  rbind(selfNoMarker, otherNoMarker, 
        selfWithMarker, otherWithMarker) %>%
  rename(Perspective = Group)

rm(otherNoMarker, otherWithMarker, 
   selfNoMarker, selfWithMarker)

```

```{r Tidying data}

#Rearrange and rename columns
dataExp2 <- 
  dataExp2 %>% 
  as_tibble() %>% 
  mutate(vasMarker = factor(
           ifelse(
             Treatment == "VAS", "Midpoint", "No Midpoint"
           )
         ),
         Sex = factor(Sex),
         Perspective = factor(Perspective)) %>%
  dplyr::select(-Treatment) %>%
  dplyr::select(ResponseId, Perspective, vasMarker, GC, ends_with("_1"), everything())

names(dataExp2)[5:34] <- sprintf("Question_%s",seq(1:30))
rm(RawData_Self_Other, RawData_VAS)

#Create long data.
dataExp2 <- 
  dataExp2 %>%
  gather(key = "Question", value = "VAS", 
         Question_1 : Question_30, factor_key = TRUE) %>%
  arrange(ResponseId) %>%
  mutate(Risk = factor(rep(rep(
    RiskLevelSequence, times = nrow(dataExp2)))),
    VAS = VAS/100)

#Exclude participants who only report at the bounds etc
dataExp2 <-
  dataExp2 %>% 
  group_by(ResponseId) %>% 
  filter(
    round(mean(VAS), 2) > 0 & 
    round(mean(VAS), 2) < 1, 
    Sex != "Other") %>%
  ungroup() %>%
  mutate(AgeZeroCenter = Age - mean(Age))

## VAS indicates on a scale from 0-100 to what extent the participant is certain 
# it is ok to go out (certain it is not alright - certain it is alright)

## Descriptives for in the paper
Descriptives <- 
  dataExp2 %>%
  group_by(Sex) %>%
  summarise(MeanAge = round(mean(Age), 1),
            SdAge = round(sd(Age, na.rm = TRUE), 1),
            n() / nrow(dataExp2))

Aggregates <- 
  dataExp2 %>%
  group_by(Perspective, vasMarker, ResponseId, Sex) %>%
  summarise(VAS = mean(VAS),
            Self_Rank = mean(GC),
            Age = mean(Age)) %>%
  ungroup() %>%
  mutate(AgeZeroCenter = Age - mean(Age))

dataExp2 <- 
  dataExp2 %>%
  mutate(Sex = factor(Sex),
         ResponseId = factor(ResponseId))
```


```{r Save data}

write_csv(dataExp2, "./data/going-out_experiment2_data.csv")


```