---
title: "Self-Isolation Experiments 2 & 3"
author: "Simon van Baal"
date: "09/08/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(afex)
library(ggplot2)
library(ggsignif)
library(stats4)
library(emmeans)
library(lawstat)
library(cowplot)
library(ggpubr)
library(grid)
library(kableExtra)
```

```{r load data, include=FALSE}
# Don't mind the errors, that's due to the column names Qualtrics creates.
RawData_Self_Other <- read_csv("Self-Isolation_Self_Other.csv")
RawData_VAS <- read_csv("Self-Isolation_VAS.csv")
```

```{r Data cleaning, include = FALSE}


#We're not too concerned with RT data for now.
Self_SO <- 
  RawData_Self_Other %>% 
  filter(Group == "Self") %>% 
  select_if(function(x) !any(is.na(x))) %>%
  select(-contains('RT'))

Other_SO <- 
  RawData_Self_Other %>%
  filter(Group == "Other") %>%
  select_if(function(x) !any(is.na(x))) %>%
  select(-contains('RT'))

Self_VAS <- 
  RawData_VAS %>% 
  filter(Group == "Self") %>% 
  select_if(function(x) !any(is.na(x))) %>%
  select(-contains('RT'))

Other_VAS <- 
  RawData_VAS %>%
  filter(Group == "Other") %>%
  select_if(function(x) !any(is.na(x))) %>%
  select(-contains('RT'))

#Now rbind the 12 datasets created.
colnames(Self_SO) <- colnames(Other_SO)
colnames(Self_VAS) <- colnames(Other_SO)
colnames(Other_VAS) <- colnames(Other_SO)

Data_follow_ups <- rbind(Self_SO, Other_SO, Self_VAS, Other_VAS)

rm(Other_SO, Other_VAS, Self_SO, Self_VAS)

#Rearrange and rename columns
Data_follow_ups <- 
  Data_follow_ups %>% 
  as_tibble() %>% 
  mutate(Perspective = factor(Group),
         Treatment = factor(Treatment),
         Gender = factor(Gender),
         Group = NULL) %>%
  select(ResponseId, Perspective, Treatment, GC, ends_with("_1"), everything())

names(Data_follow_ups)[5:34] <- sprintf("Question_%s",seq(1:30))
rm(RawData_Self_Other, RawData_VAS)

#Create long data.
Data_follow_ups <- 
  Data_follow_ups %>%
  gather(key = "Question", value = "VAS", Question_1 : Question_30, factor_key = TRUE) %>%
  arrange(ResponseId) %>%
  mutate(Risk = factor(rep(rep(c("High Risk", "Minimal Risk", "Low Risk"), each = 10), times = nrow(Data_follow_ups))))

#Exclude participants who only report at the bounds
Data_follow_ups <-
  Data_follow_ups %>% 
  group_by(ResponseId) %>% 
  filter(
    round(mean(VAS)) > 0 & 
    round(mean(VAS)) < 100, 
    Gender != "Other") %>%
  ungroup() %>%
    mutate(AgeZeroCenter = Age - mean(Age))

## VAS indicates on a scale from 0-100 to what extent the participant is certain it is ok to go out (certain it is not alright - certain it is alright)

## Descriptives for in the paper
Descriptives <- Data_follow_ups %>%
  group_by(Gender) %>%
  summarise(MeanAge = round(mean(Age), 1),
            SdAge = round(sd(Age, na.rm = TRUE), 1),
            n()/nrow(Data_follow_ups)
            )
Descriptives

Aggregates <- Data_follow_ups %>%
  group_by(Perspective, Treatment, ResponseId, Gender) %>%
  summarise(VAS = mean(VAS),
            Self_Rank = mean(GC),
            Age = mean(Age)) %>%
  ungroup() %>%
  mutate(AgeZeroCenter = Age - mean(Age))
```




```{r Analysis, include = TRUE}
emm_options(pbkrtest.limit = 100000)

#write.csv2(Data, "Self-IsolationDataExp2and3")

Data_follow_ups %>% group_by(Treatment, Perspective) %>% summarise(n = n())

###### Mixed Anova
mAnovaExp2n3 <- afex::aov_ez("ResponseId","VAS",
                      data = Data_follow_ups, 
                      between=c("Treatment", "Perspective", "Gender"),
                      within=c("Risk"),
                      covariate = "AgeZeroCenter",
                      observed = c("Gender","AgeZeroCenter"),
                      fun_aggregate = mean,
                      factorize = F)
nice(mAnovaExp2n3)



mAnova2 <- afex::aov_ez("ResponseId","Self_Rank",
                      data = Aggregates, 
                      between=c("Treatment", "Perspective", "Gender"),
                      covariate = c("AgeZeroCenter", "VAS"),
                      fun_aggregate = mean,
                      factorize = F)
nice(mAnova2)

cor.test(Aggregates$Self_Rank, Aggregates$VAS)

#### Risk Factor analysis

RiskEmm_Exp2n3 <- emmeans(mAnovaExp2n3, specs = "Risk")
RiskTable_Exp2n3 <- 
  Data_follow_ups %>% 
  group_by(Risk) %>% 
  summarise(Mean = round(mean(VAS),2),
            St.dev = round(sd(VAS),2),
            n = n()/30)
RiskPairs_Exp2n3 <- pairs(RiskEmm_Exp2n3, reverse = F, adjust = "fdr")

#RiskEmm
RiskPairs_Exp2n3
confint(RiskPairs_Exp2n3)
RiskTable_Exp2n3

##### Perspective factor analysis

GenderEmm_Exp2n3 <- emmeans(mAnovaExp2n3, specs = c("Gender"))
summary(GenderEmm_Exp2n3)
pairs(GenderEmm_Exp2n3)
PerspectiveTreatmentTable_Exp2n3 <- Data_follow_ups %>% group_by(Gender) %>% summarise(Mean = round(mean(VAS), 2),
                                                            St.dev = round(sd(VAS), 2),
                                                            n = n()/30)
PerspectivePairs_Exp2n3 <- pairs(PerspectiveTreatmentEmm_Exp2n3, reverse = T, adjust = "fdr")

#PerspectiveEmm
PerspectivePairs_Exp2n3
#confint(PerspectivePairs)
PerspectiveTreatmentTable_Exp2n3

## Risk x Age trend analysis.
emtrends(mAnovaExp2n3, 'Risk', 'AgeZeroCenter', adjust = 'fdr')
pairs(emtrends(mAnovaExp2n3, 'Risk', 'AgeZeroCenter'), adjust = 'fdr', infer = c(T, T))
confint(pairs(emtrends(mAnovaExp2n3, 'Risk', 'AgeZeroCenter'), adjust = 'fdr'))

#ggplot(data = Data, aes(x = VAS, y = Question)) +
#  geom_boxplot()

#ggplot(data = Data, aes(x = Question, y = VAS)) +
#  geom_point(position = "jitter", size = 0.1)

Aggregates %>% group_by(Treatment) %>% summarise(mean = mean(Self_Rank),
                                                   sd = sd(Self_Rank))

MWtest <- wilcox.test(Aggregates$Self_Rank, mu = 50, alternative = 'greater')
wilcox.test(Aggregates$Self_Rank, mu = 50, conf.int = T, conf.level = .95)

Z = qnorm(MWtest$p.value)
Z

bf.test(VAS ~ Treatment, data = Aggregates)

AggregatesExp1 <- 
  Data %>% group_by(ResponseId) %>% summarise(Mean = mean(VAS), SD = sd(VAS))
experimentComparison <- 
  BayesFactor::ttestBF(Aggregates$VAS, AggregatesExp1$Mean)
summary(experimentComparison)
plot(AggregatesExp1$Mean, Aggregates$VAS)

```


```{r Assessing support for null findings}
# Perspective factor
model0 <- lmer(VAS ~ 
                 Perspective +
                 Gender +
                 AgeZeroCenter + 
                 Risk +
                 (1|ResponseId), 
               data = Data_follow_ups)

model1 <- lmer(VAS ~ 
                 Treatment + 
                 Gender +
                 AgeZeroCenter + 
                 Risk +
                 (1|ResponseId), 
               data = Data_follow_ups)
model2 <- lmer(VAS ~ 
                 Perspective + 
                 Treatment +
                 Gender +
                 AgeZeroCenter + 
                 Risk +
                 (1|ResponseId), 
               data = Data_follow_ups)
model3 <- lmer(VAS ~
                 Gender +
                 AgeZeroCenter +
                 Risk +
                 (1|ResponseId),
               data = Data_follow_ups)

bayesModels <- bayesfactor_models(model0, model1, model2, model3, denominator = 4)
bayesfactor_inclusion(bayesModels)


```




```{r Graphs}
Data_follow_ups <- 
  Data_follow_ups %>% 
  mutate(PerspectiveNumeric = ifelse(Perspective == "Self", 1, 0))

# The palette with black:
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
cbbPaletteBoxPlots <- c("#E69F00","#56B4E9","#000000")
## Plot dimensions
w = 6
h = 4

VAS_Density <- 
  ggplot(Data_follow_ups %>% filter(Treatment == "VAS"), 
         aes(x = VAS, fill = Perspective)) +
  geom_density(alpha = 0.4) +
  geom_boxplot(aes(x = VAS, y = PerspectiveNumeric * -0.0015 + 0.05), alpha = .4, colour = "black",notch = TRUE, coef = 1 ) +
  labs(title = "VAS Midpoint") + 
  ylab("Density") + 
  xlab("Permissiveness") +
  scale_fill_manual(values = cbbPalette) +
  theme_light()

Self_Other_Density <- 
  ggplot(Data_follow_ups %>% filter(Treatment == "Self-Other"), 
         aes(x = VAS, fill = Perspective)) +
  geom_density(alpha = 0.4) +
  geom_boxplot(aes(x = VAS, y = PerspectiveNumeric * -0.0015 + 0.05), alpha = .4, colour = "black",notch = TRUE, coef = 1 ) +
  labs(title = "Control Treatment") + 
  ylab("Density") + 
  xlab("Permissiveness") +
  scale_fill_manual(values = cbbPalette) +
  theme_light()

TreatmentPlots <- ggarrange(VAS_Density, Self_Other_Density, labels = c("A", "B"), nrow = 1, ncol = 2, common.legend = TRUE, legend = "bottom") +
  ggsave("DensityPlotExp2and3.png", width = 2*w, height = 1.3*h) 

################# Density plot of VAS per group
a <- 
  ggplot(Data_follow_ups %>% filter(Treatment == "VAS", Risk == "High Risk"), 
         aes(x = VAS, fill = Perspective)) +
  geom_density(alpha = 0.4) +
  geom_boxplot(aes(x = VAS, y = PerspectiveNumeric * -0.0015 + 0.05), alpha = .4, colour = "black",notch = TRUE, coef = 1 ) +
  labs(title = "VAS Midpoint, High Risk") + 
  ylab("Density") + 
  xlab("Permissiveness") +
  theme_light()

b <- 
  ggplot(Data_follow_ups %>% filter(Treatment == "VAS", Risk == "Low Risk"), 
         aes(x = VAS, fill = Perspective)) +
  geom_density(alpha = 0.4) +
  geom_boxplot(aes(x = VAS, y = PerspectiveNumeric * -0.0015 + 0.05), alpha = .4, colour = "black",notch = TRUE, coef = 1 ) +
  labs(title = "VAS Midpoint, Low Risk") + 
  ylab("Density") + 
  xlab("Permissiveness") +
  theme_light()

c <- 
  ggplot(Data_follow_ups %>% filter(Treatment == "VAS", Risk == "Minimal Risk"), 
         aes(x = VAS, fill = Perspective)) +
  geom_density(alpha = 0.4) +
  geom_boxplot(aes(x = VAS, y = PerspectiveNumeric * -0.0015 + 0.05), alpha = .4, colour = "black",notch = TRUE, coef = 1 ) +
  labs(title = "VAS Midpoint, Minimal Risk") + 
  ylab("Density") + 
  xlab("Permissiveness") +
  theme_light()

d <- 
  ggplot(Data_follow_ups %>% filter(Treatment == "Self-Other", Risk == "High Risk"), 
         aes(x = VAS, fill = Perspective)) +
  geom_density(alpha = 0.4) +
  geom_boxplot(aes(x = VAS, y = PerspectiveNumeric * -0.0015 + 0.05), alpha = .4, colour = "black",notch = TRUE, coef = 1 ) +
  labs(title = "No Midpoint, High Risk") + 
  ylab("Density") + 
  xlab("Permissiveness") +
  theme_light()

e <- 
  ggplot(Data_follow_ups %>% filter(Treatment == "Self-Other", Risk == "Low Risk"), 
         aes(x = VAS, fill = Perspective)) +
  geom_density(alpha = 0.4) +
  geom_boxplot(aes(x = VAS, y = PerspectiveNumeric * -0.0015 + 0.05), alpha = .4, colour = "black",notch = TRUE, coef = 1 ) +
  labs(title = "No Midpoint, Low Risk") + 
  ylab("Density") + 
  xlab("Permissiveness") +
  theme_light()

f <- 
  ggplot(Data_follow_ups %>% filter(Treatment == "Self-Other", Risk == "Minimal Risk"), 
         aes(x = VAS, fill = Perspective)) +
  geom_density(alpha = 0.4) +
  geom_boxplot(aes(x = VAS, y = PerspectiveNumeric * -0.0015 + 0.05), alpha = .4, colour = "black",notch = TRUE, coef = 1 ) +
  labs(title = "No Midpoint, Minimal Risk") + 
  ylab("Density") + 
  xlab("Permissiveness") +
  theme_light()


RiskPlots_Exp2n3 <- ggarrange(a, b, c, d, e, f ,labels = c("A", "B", "C", "D", "E", "F"), nrow = 2, ncol = 3, common.legend = TRUE, legend = "bottom") +
  ggsave("RiskPlotsExp2and3.png", width = 3*w, height = 2.5*h) 

RiskPlots_Exp2n3
################################################## Box Plots


#boxRiskExp2 <- 
  ggplot(Data_follow_ups %>% mutate(Risk = factor(Risk, levels = c("Minimal Risk", "Low Risk", "High Risk"))),
       aes(x = VAS, y = Risk, fill = Risk)) +
  geom_boxplot(position = position_nudge(y = 0.25), outlier.shape = NA, notch = TRUE, width = 0.2) +
  geom_point(position = position_jitter(height = 0.1), size = .15, col = "darkgrey") +
  annotate("segment", 
           x = c(-3,-3,-8), 
           xend = c(-3,-3,-8), 
           y = c(1.23,2.27, 1.20), 
           yend = c(2.22, 3.22, 3.30),
           size = .8) +
  annotate("text", x = c(-3.5, -3.5, -9), y = c(1.75, 2.75, 2.25), label = "***", angle = 90, size = 7) +
  labs(title = "Permissiveness by Risk Level") +
  xlab("Permissiveness") + ylab("Risk Level") +
  xlim(-10, 100.5) +
  scale_fill_brewer(palette = "YlOrRd") +
  guides(fill = guide_legend(reverse = TRUE)) +
  theme_light()
boxRiskExp2

```



```{r Plots continued #2}

RiskAggregates <- 
  Data_follow_ups %>%
  group_by(ResponseId, Risk) %>%
  summarise(VAS = mean(VAS),
            Age = mean(Age)) %>%
  ungroup()

AgeGenderPlot_Exp2n3 <- 
  ggplot(Aggregates) +
    aes(x = Age, y = VAS, col = Gender) +
    geom_point() +
    geom_smooth(method = "lm") +
    labs(y = "Permissiveness") +
    scale_color_manual(values = cbbPalette) +
    theme_light()
AgeGenderPlot_Exp2n3

AgeRiskPlot_Exp2n3 <-
  ggplot(RiskAggregates) +
    aes(x = Age, y = VAS, col = Risk) +
    geom_point(size = 1) +
    geom_smooth(method = "lm") +
    labs(y = "Permissiveness") +
    scale_color_manual(values = cbbPalette) +
    theme_light()
AgeRiskPlot_Exp2n3

PlotsAge_Exp2n3 <- 
  ggarrange(AgeRiskPlot_Exp2n3, AgeGenderPlot_Exp2n3 ,labels = c("A", "B"), nrow = 1, ncol = 2, common.legend = FALSE, legend = "bottom") +
  ggsave("AgePlotsExp2and3.png", width = 2*w, height = 1.3*h) 

Aggregates <-
  Aggregates %>% arrange(VAS) %>% mutate(VAS_Rank = seq(1:nrow(Aggregates))/nrow(Aggregates)*100)


```


```{r Table}
tdfExp2 <- Data_follow_ups %>% group_by(Treatment, Perspective, Risk) %>%
  summarise(Mean = round(mean(VAS),2),
            SD = round(sd(VAS),2)) %>%
  arrange(desc(Treatment), desc(Risk), desc(Perspective)) %>%
  ungroup()

tdf1Exp2 <- 
  tdfExp2 %>% 
  filter(Risk == "Minimal Risk") %>% 
  select(Perspective, Mean, SD) %>%
  rename(` ` = Perspective)

tdf2Exp2 <- 
  tdfExp2 %>% 
  filter(Risk == "Low Risk") %>% select(Mean, SD)

tdf3Exp2 <- 
  tdfExp2 %>% 
  filter(Risk == "High Risk") %>% select(Mean, SD)

cbind(tdf1Exp2, tdf2Exp2, tdf3Exp2) %>% 
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), 
                full_width = T, 
                font_size = 14) %>%
  column_spec(c(1:2,4,6), color = "black") %>%
  add_header_above(c(" " = 1, "High" = 2, "Low" = 2, "Minimal" = 2), align = "justify") %>%
  add_header_above(c(" " = 1, "Risk" = 6), font_size = 18, align = "justify") %>%
  pack_rows(group_label = "Midpoint Marker", 
            start_row = 1, 
            end_row = 2,
            label_row_css = "background-color: #777; color: #fff;") %>%
  pack_rows(group_label = "No Marker", 
            start_row = 3, 
            end_row = 4, 
            label_row_css = "background-color: #777; color: #fff;") %>%
  save_kable(file = "TableExp2.png")









```


